### ISSUE TITLE
List Events: .attendees[].name is = to email for INTERNAL attendees

### ISSUE THREAD

**Issue by w-le** [place-labs/google-staff-api#15]
List Events: .attendees[].name is = to email for INTERNAL attendees

After last week's changes, external attendees now correctly have their `name` equal to the placeos guest name (instead of the email)

However INTERNAL attendees .name are still being returned as the email address instead of the staff name.
see internal attendee `1` below, which exhibits the issue:
(deleted image of response to LIST EVENTs)

while attendee `2` (external) has a proper name (due to last week's fix)

**Comment by w-le** [comment]
turns out the event in question was created BEFORE last week's fix was applied.

So I've reference an up to date event, which shows
- name for external attendees is returned OK
- name for internal attendees is returned OK
- name for the HOST is returned as the email address

**Comment by w-le** [comment]
so turns out that this is expected staff-api behaviour, though is not obvious/intuitive in my opinion.

POST Event
- attendees[] does not include the host{}
  - resulting google event includes the host in the attendee list, but is missing the name (only the host's email will be displayed)

POST Event
- attendees[] does include the host{}
  - resulting google event includes the host in the attendee list and uses the corresponding attendees[].name

I think we should allow the frontend to determine whether the Host should be included as an attendee or not (via a checkbox), and if NOT (first bullet point above), then frontend should not include the host the attendees[] param (i.e. same as what it's doing currently), and staff-api should not automatically add the host to the google event's attendees[].

IF the end user does want the host included in the attendees list (we can make this the default), the frontend will need to include it in attendees[], with .name.

Most importantly, this behaviour should be documented in the apiary, as right now it's an unexpected surprise for internal testers and external developes

**Comment by jeremyw24** [comment]
@w-le believe this to be solved, please re-open if it is still an issue.
