### ISSUE TITLE
After editing an event and setting event.attendees[].visit_expected to false, the response still has visit_expected true

### ISSUE THREAD

**Issue by w-le** [place-labs/google-staff-api#19]
After editing an event and setting event.attendees[].visit_expected to false, the response still has visit_expected true

So atm it is impossible change an event's attendee's visit_expected from true to false.

I tried looking at the controllers/events.cr code to debug this, but it's really hard to trace:
https://github.com/place-labs/google-staff-api/blob/fix/event%2Fguests/src/controllers/events.cr#L341-L700

Are you able to help make a change to event update such that when a guest to set to visit_expected: false, that correctly persists?

**Comment by stakach** [comment]
fixed by #20
