### ISSUE TITLE
all-day events are returned as one day EARLIER than the time/date they were created for

### ISSUE THREAD

**Issue by w-le** [place-labs/google-staff-api#3]
In a POST to create an all-day event, the frontend will specify a start_epoch of the current time or midnight of the current day in the current timezone, and then an end_epoch of 24hrs after that start_epoch.

In the response and all subsequent Gets of the resulting event, the start/end epochs are for 12am-12am GMT (which is fine) but of the PREVIOUS day than what was posted.

Example:
- I create an all day event for TUESDAY, the Post start/end epochs are now and now+24hrs respectively
- In the resulting RESPONSE, the start/end epochs are 12am-12am MONDAY, GMT time.
- Note that even if the event was Posted on TUESDAY GMT time (i.e. after 10am SYD time), the resulting event will still be 1 day earlier than desired

**Comment by stakach** [comment]
fixed in 31d646be006ae73bb6b39322dc236cb579c56ad3
