### ISSUE TITLE
All day events created on calendar.google.com return as all_day: false by staff-api

### ISSUE THREAD

**Issue by w-le** [place-labs/google-staff-api#6]
See this screenshot of staff-api's response to /events/  , where this particular event was created as all day on calendar.google.com yet has all_day is false

![image](https://user-images.githubusercontent.com/10395560/117226639-a6d7be80-ae47-11eb-804e-4ceb0e4573d4.png)

**Comment by w-le** [comment]
Interesting to note that that all_day event created in google calendar has  a start epoch that is NOT 12am GMT

**Comment by stakach** [comment]
yeah, they are not "real" all day events - they are returning start and end times instead of just the dates

**Comment by stakach** [comment]
possibly all-day events in the true senses are just there for exchange / ical support

**Comment by w-le** [comment]
resolved and tested OK
