### ISSUE TITLE
Staff App>My day> Event timings are incorrect for meetings in My Day

### ISSUE THREAD

**Issue by ksra08** [place-labs/google-staff-api#7]
**Describe the bug**![image](https://user-images.githubusercontent.com/78706760/117237111-8e7a9a80-ae6d-11eb-915d-f1e0afa67b89.png)Created a meeting for 12.30pm from Sydney timezone. Timings are returned correctly in concierge. But in Staff App>My Day events return incorrect start and end times.![image](https://user-images.githubusercontent.com/78706760/117237126-96d2d580-ae6d-11eb-866a-3f71bcc0a5bc.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/78706760/117237111-8e7a9a80-ae6d-11eb-915d-f1e0afa67b89.png)

![image](https://user-images.githubusercontent.com/78706760/117237126-96d2d580-ae6d-11eb-866a-3f71bcc0a5bc.png)

Request url for concierge : https://mysmartoffice-stg.mer.pwc.com/api/staff/v1/events?zone_ids=zone-FBkxA1Php8u&period_start=1620223200&period_end=1620309599

Request url for staff app: https://mysmartoffice-stg.mer.pwc.com/api/staff/v1/events?calendars=william.le@testenv.pwc.com&period_start=1620223200&period_end=1621519199
@stakach

**Comment by stakach** [comment]
it's returning the events from different calendars
the data comes straight from google, so it means the event was moved on the resource calendar and not in the owners calendar
